version: 0.2
env:
  variables:
    AWS_ACCOUNT_ID: "448397505685"   # Replace with your AWS account ID
    AWS_DEFAULT_REGION: "us-east-1" # Replace with your region
    IMAGE_REPO_NAME: "nginx-application-repository"
    IMAGE_TAG: "latest"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - ACCOUNT_ID=$(aws sts get-caller-identity --query account --output text)
      - REGION=$AWS_DEFAULT_REGION
      - REPOSITORY_NAME=nginx-application-repository   # <-- change to your ECR repo name
      - IMAGE_TAG=$(date +%Y%m%d%H%M%S)
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_NAME:$IMAGE_TAG .
      - docker tag $REPOSITORY_NAME:$IMAGE_TAG $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$REPOSITORY_NAME:$IMAGE_TAG

  post_build:
    commands:
      - echo Pushing the Docker image to Amazon ECR...
      - docker push $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$REPOSITORY_NAME:$IMAGE_TAG
      - echo Creating imagedefinitions.json file for ECS...
      - printf '[{"name":"nginx-container","imageUri":"%s"}]' $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$REPOSITORY_NAME:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
